#  Configuration file for tpDcc-tools-nameit

# List of categories for renamer
categories: []

# List of DCC nodes that should be discarded during renaming process
nodes_to_discard: []

# List of DCC types that should be discarded during renaming process
types_to_discard: []